cc_binary(
    name = "graph",
    srcs = [
        "graph.cc",
        "graph.h",
        "main.cpp",
    ],
    deps = ["//input:input_lib"],
)

cc_library(
    name = "graph_lib",
    srcs = [
        "graph.cc",
        "graph.h",
    ],
    visibility = ["//visibility:public"],
)
