cc_binary(
    name = "state",
    srcs = [
        "state.cpp",
        "state.h",
    ],
    deps = ["//graph:graph_lib"],
)

cc_library(
    name = "state_lib",
    srcs = [
        "state.cpp",
        "state.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//graph:graph_lib"],
)
