cc_binary(
    name = "solver",
    srcs = [
        "solver.cpp",
        "solver.h",
    ],
    deps = [
        "//input:input_lib",
        "//state:state_lib",
        "//tqdm:tqdm_lib",
    ],
)
